-- 댓글
CREATE TABLE TB_COMMENT (
    COMMENT_ID NUMBER NOT NULL PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(500),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_COMMENT IS '댓글';
COMMENT ON COLUMN TB_COMMENT.COMMENT_ID IS '댓글 ID';
COMMENT ON COLUMN TB_COMMENT.POST_ID IS '댓글 달린 게시글 ID';
COMMENT ON COLUMN TB_COMMENT.USER_ID IS '댓글 작성자 ID';
COMMENT ON COLUMN TB_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN TB_COMMENT.CREATED_DATE IS '댓글 생성일시';
COMMENT ON COLUMN TB_COMMENT.CREATED_ID IS '댓글 생성 ID';
COMMENT ON COLUMN TB_COMMENT.UPDATED_DATE IS '댓글 수정일시';
COMMENT ON COLUMN TB_COMMENT.UPDATED_ID IS '댓글 수정 ID';

-- 댓글 시퀀스
CREATE SEQUENCE SEQ_TB_COMMENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE;