-- 댓글 좋아요
CREATE TABLE TB_COMMENT_LIKE (
    COMMENT_LIKE_ID NUMBER NOT NULL PRIMARY KEY,
    COMMENT_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE TB_COMMENT_LIKE IS '댓글 좋아요';
COMMENT ON COLUMN TB_COMMENT_LIKE.COMMENT_LIKE_ID IS '댓글 좋아요 ID';
COMMENT ON COLUMN TB_COMMENT_LIKE.COMMENT_ID IS '좋아요 대상 댓글 ID';
COMMENT ON COLUMN TB_COMMENT_LIKE.USER_ID IS '좋아요 누른 사용자 ID';
COMMENT ON COLUMN TB_COMMENT_LIKE.CREATED_DATE IS '좋아요 생성 일시';

-- 댓글 좋아요 시퀸스
CREATE SEQUENCE SEQ_TB_COMMENT_LIKE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE INDEX IDX_COMMENT_LIKE_COMMENT_ID ON TB_COMMENT_LIKE (COMMENT_ID);
CREATE INDEX IDX_COMMENT_LIKE_USER_ID ON TB_COMMENT_LIKE (USER_ID);