-- 팔로우
CREATE TABLE TB_FOLLOW (
    FOLLOWER_ID NUMBER NOT NULL,
    FOLLOWING_ID NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100),
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID)
);

COMMENT ON TABLE TB_FOLLOW IS '팔로우';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWER_ID IS '팔로우를 하는 사용자 ID';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWING_ID IS '팔로우를 받는 사용자 ID';
COMMENT ON COLUMN TB_FOLLOW.CREATED_DATE IS '팔로우 관계 생성일시';
COMMENT ON COLUMN TB_FOLLOW.CREATED_ID IS '팔로우 관게 생성 ID';
COMMENT ON COLUMN TB_FOLLOW.UPDATED_DATE IS '팔로우 관계 수정일시';
COMMENT ON COLUMN TB_FOLLOW.UPDATED_ID IS '팔로우 관계 수정 ID';