-- 좋아요
CREATE TABLE TB_LIKE (
    LIKE_ID NUMBER NOT NULL PRIMARY KEY,
    USER_ID NUMBER,
    POST_ID NUMBER,
    RESTAURANT_ID NUMBER,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100),
    CONSTRAINT CHK_LIKE_TARGET CHECK (
        (POST_ID IS NOT NULL AND RESTAURANT_ID IS NULL) OR
        (POST_ID IS NULL AND RESTAURANT_ID IS NOT NULL)
    )
);

COMMENT ON TABLE TB_LIKE IS '좋아요';
COMMENT ON COLUMN TB_LIKE.LIKE_ID IS '좋아요 ID';
COMMENT ON COLUMN TB_LIKE.USER_ID IS '사용자 ID';
COMMENT ON COLUMN TB_LIKE.POST_ID IS '게시글 ID';
COMMENT ON COLUMN TB_LIKE.RESTAURANT_ID IS '좋아요 대상 맛집 ID';
COMMENT ON COLUMN TB_LIKE.CREATED_DATE IS '좋아요 생성 일시';
COMMENT ON COLUMN TB_LIKE.CREATED_ID IS '좋아요 생성 ID';
COMMENT ON COLUMN TB_LIKE.UPDATED_DATE IS '좋아요 수정 일시';
COMMENT ON COLUMN TB_LIKE.UPDATED_ID IS '좋아요 수정 ID';

-- 좋아요 시퀀스
CREATE SEQUENCE SEQ_TB_LIKE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
