-- 공지사항
CREATE TABLE TB_NOTICE (
    NOTICE_ID NUMBER NOT NULL PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    NOTICE_TITLE VARCHAR2(200) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_NOTICE IS '공지사항';
COMMENT ON COLUMN TB_NOTICE.NOTICE_ID IS '공지사항 ID';
COMMENT ON COLUMN TB_NOTICE.USER_ID IS '공지사항 작성자';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN TB_NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN TB_NOTICE.CREATED_DATE IS '공지사항 생성 일시';
COMMENT ON COLUMN TB_NOTICE.CREATED_ID IS '공지사항 생성 ID';
COMMENT ON COLUMN TB_NOTICE.UPDATED_DATE IS '공지사항 수정 일시';
COMMENT ON COLUMN TB_NOTICE.UPDATED_ID IS '공지사항 수정 ID';

-- 공지사항 시퀀스
CREATE SEQUENCE SEQ_TB_NOTICE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;