-- 게시글 이미지
CREATE TABLE TB_POST_IMAGE (
    IMAGE_ID NUMBER NOT NULL PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    IMAGE_URL VARCHAR2(500) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_POST_IMAGE IS '게시글 이미지';
COMMENT ON COLUMN TB_POST_IMAGE.IMAGE_ID IS '이미지 ID';
COMMENT ON COLUMN TB_POST_IMAGE.POST_ID IS '게시글 ID';
COMMENT ON COLUMN TB_POST_IMAGE.IMAGE_URL IS '이미지 URL';
COMMENT ON COLUMN TB_POST_IMAGE.CREATED_DATE IS '이미지 생성 일시';
COMMENT ON COLUMN TB_POST_IMAGE.CREATED_ID IS '이미지 생성 ID';
COMMENT ON COLUMN TB_POST_IMAGE.UPDATED_DATE IS '이미지 수정 일시';
COMMENT ON COLUMN TB_POST_IMAGE.UPDATED_ID IS '이미지 수정 ID';

-- 게시글 이미지 시퀀스
CREATE SEQUENCE SEQ_TB_POST_IMAGE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;