-- 게시글
CREATE TABLE TB_POST (
    POST_ID NUMBER NOT NULL PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    RESTAURANT_ID NUMBER NOT NULL,
    POST_TITLE VARCHAR2(200),
    POST_CONTENT CLOB,
    LOCATION_TAG VARCHAR2(100),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100),
    COMMENT_COUNT NUMBER DEFAULT 0
);

COMMENT ON TABLE TB_POST IS '게시글';
COMMENT ON COLUMN TB_POST.POST_ID IS '게시글 ID';
COMMENT ON COLUMN TB_POST.USER_ID IS '게시글 작성자';
COMMENT ON COLUMN TB_POST.RESTAURANT_ID IS '맛집 ID';
COMMENT ON COLUMN TB_POST.POST_TITLE IS '게시글 제목';
COMMENT ON COLUMN TB_POST.POST_CONTENT IS '게시글 내용';
COMMENT ON COLUMN TB_POST.LOCATION_TAG IS '위치 태그';
COMMENT ON COLUMN TB_POST.CREATED_DATE IS '게시글 생성 일시';
COMMENT ON COLUMN TB_POST.CREATED_ID IS '게시글 생성 ID';
COMMENT ON COLUMN TB_POST.UPDATED_DATE IS '게시글 수정 일시';
COMMENT ON COLUMN TB_POST.UPDATED_ID IS '게시글 수정 ID';
COMMENT ON COLUMN TB_POST.COMMENT_COUNT IS '게시글 댓글 개수';

-- 게시글 시퀀스
CREATE SEQUENCE SEQ_TB_POST
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

