-- 게시글, 태그
CREATE TABLE TB_POST_TAG (
    POST_ID NUMBER NOT NULL,
    TAG_ID NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100),
    PRIMARY KEY (POST_ID, TAG_ID)
);

COMMENT ON TABLE TB_POST_TAG IS '포스트, 태그 관계';
COMMENT ON COLUMN TB_POST_TAG.POST_ID IS '게시글 ID';
COMMENT ON COLUMN TB_POST_TAG.TAG_ID IS '태그 ID';
COMMENT ON COLUMN TB_POST_TAG.CREATED_DATE IS '관계 생성 일시';
COMMENT ON COLUMN TB_POST_TAG.CREATED_ID IS '관계 생성 ID';
COMMENT ON COLUMN TB_POST_TAG.UPDATED_DATE IS '관계 수정 일시';
COMMENT ON COLUMN TB_POST_TAG.UPDATED_ID IS '관계 수정 ID';

-- 게시글 시퀸스
CREATE SEQUENCE TB_POST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;