-- 신고
CREATE TABLE TB_REPORT (
    REPORT_ID NUMBER NOT NULL PRIMARY KEY,
    REPORTER_ID NUMBER NOT NULL,
    TARGET_ID NUMBER,
    REPORT_TYPE VARCHAR2(20) NOT NULL,
    REPORT_REASON VARCHAR2(500),
    STATUS VARCHAR2(20),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_REPORT IS '신고';
COMMENT ON COLUMN TB_REPORT.REPORT_ID IS '신고 ID';
COMMENT ON COLUMN TB_REPORT.REPORTER_ID IS '신고한 사용자 ID';
COMMENT ON COLUMN TB_REPORT.TARGET_ID IS '신고 대상 사용자 ID';
COMMENT ON COLUMN TB_REPORT.REPORT_TYPE IS '신고 유형';
COMMENT ON COLUMN TB_REPORT.REPORT_REASON IS '신고 사유';
COMMENT ON COLUMN TB_REPORT.STATUS IS '신고 처리';
COMMENT ON COLUMN TB_REPORT.CREATED_DATE IS '신고 접수 일시';
COMMENT ON COLUMN TB_REPORT.CREATED_ID IS '신고 접수 ID';
COMMENT ON COLUMN TB_REPORT.UPDATED_DATE IS '신고 처리 완료 일시';
COMMENT ON COLUMN TB_REPORT.UPDATED_ID IS '신고 처리 ID';