-- 지역 정보 테이블
CREATE TABLE TB_REGION (
    REGION_ID NUMBER NOT NULL PRIMARY KEY,
    REGION_NAME VARCHAR2(100) NOT NULL UNIQUE,
    REGION_DESCRIPTION CLOB,
    VIEW_COUNT NUMBER DEFAULT 0,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_REGION IS '지역 정보';
COMMENT ON COLUMN TB_REGION.REGION_ID IS '지역 고유 ID';
COMMENT ON COLUMN TB_REGION.REGION_NAME IS '지역 이름';
COMMENT ON COLUMN TB_REGION.REGION_DESCRIPTION IS '지역 설명';
COMMENT ON COLUMN TB_REGION.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN TB_REGION.CREATED_DATE IS '생성 일시';
COMMENT ON COLUMN TB_REGION.CREATED_ID IS '생성 사용자 ID';
COMMENT ON COLUMN TB_REGION.UPDATED_DATE IS '수정 일시';
COMMENT ON COLUMN TB_REGION.UPDATED_ID IS '수정 사용자 ID';

-- 지역 정보 시퀀스
CREATE SEQUENCE SEQ_TB_REGION
    START WITH 1
    INCREMENT BY 1
    NOCACHE;