-- 맛집
CREATE TABLE TB_RESTAURANT (
    RESTAURANT_ID NUMBER NOT NULL PRIMARY KEY,
    RESTAURANT_NAME VARCHAR2(100) NOT NULL,
    ADDR_SIDO VARCHAR2(30) NOT NULL,
    ADDR_SIGUNGU VARCHAR2(30) NOT NULL,
    ADDR_DONG VARCHAR2(30) NOT NULL,
    ADDR_DETAIL VARCHAR2(200) NOT NULL,
    PHONE_NUMBER VARCHAR2(30),
    RESTAURANT_CATEGORY VARCHAR2(100),
    RESTAURANT_LAT NUMBER(10, 7),
    RESTAURANT_LON NUMBER(10, 7),
    OPEN_HOUR NUMBER(2),
    OPEN_MINUTE NUMBER(2),
    CLOSE_HOUR NUMBER(2),
    CLOSE_MINUTE NUMBER(2),
    BREAK_START_HOUR NUMBER(2),
    BREAK_START_MINUTE NUMBER(2),
    BREAK_END_HOUR NUMBER(2),
    BREAK_END_MINUTE NUMBER(2),
    RESTAURANT_HOLIDAY VARCHAR2(100),
    PARKING_INFO VARCHAR2(200),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_RESTAURANT IS '맛집 정보';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_ID IS '맛집 ID';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_NAME IS '맛집 이름';
COMMENT ON COLUMN TB_RESTAURANT.ADDR_SIDO IS '맛집 주소(시/도)';
COMMENT ON COLUMN TB_RESTAURANT.ADDR_SIGUNGU IS '맛집 주소(시/군/구)';
COMMENT ON COLUMN TB_RESTAURANT.ADDR_DONG IS '맛집 주소(동/읍/면)';
COMMENT ON COLUMN TB_RESTAURANT.ADDR_DETAIL IS '주소 상세';
COMMENT ON COLUMN TB_RESTAURANT.PHONE_NUMBER IS '맛집 전화번호';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_CATEGORY IS '음식 카테고리';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_LAT IS '맛집 위치 위도';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_LON IS '맛집 위치 경도';
COMMENT ON COLUMN TB_RESTAURANT.OPEN_HOUR IS '영업 시작 시';
COMMENT ON COLUMN TB_RESTAURANT.OPEN_MINUTE IS '영업 시작 분';
COMMENT ON COLUMN TB_RESTAURANT.CLOSE_HOUR IS '영업 종료 시';
COMMENT ON COLUMN TB_RESTAURANT.CLOSE_MINUTE IS '영업 종료 분';
COMMENT ON COLUMN TB_RESTAURANT.BREAK_START_HOUR IS '브레이크 시작 시';
COMMENT ON COLUMN TB_RESTAURANT.BREAK_START_MINUTE IS '브레이크 시작 분';
COMMENT ON COLUMN TB_RESTAURANT.BREAK_END_HOUR IS '브레이크 종료 시';
COMMENT ON COLUMN TB_RESTAURANT.BREAK_END_MINUTE IS '브레이크 종료 분';
COMMENT ON COLUMN TB_RESTAURANT.RESTAURANT_HOLIDAY IS '휴무일';
COMMENT ON COLUMN TB_RESTAURANT.PARKING_INFO IS '주차 정보';
COMMENT ON COLUMN TB_RESTAURANT.CREATED_DATE IS '맛집 정보 생성 일시';
COMMENT ON COLUMN TB_RESTAURANT.CREATED_ID IS '맛집 정보 생성 ID';
COMMENT ON COLUMN TB_RESTAURANT.UPDATED_DATE IS '맛집 정보 수정 일시';
COMMENT ON COLUMN TB_RESTAURANT.UPDATED_ID IS '맛집 정보 수정 ID';