-- 리뷰
CREATE TABLE TB_REVIEW (
    REVIEW_ID NUMBER NOT NULL PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    RESTAURANT_ID NUMBER NOT NULL,
    REVIEW_RATING NUMBER(2, 1) NOT NULL,
    REVIEW_CONTENT CLOB NOT NULL,
    AI_SUMMARY CLOB,
    AI_KEYWORDS VARCHAR2(500),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_REVIEW IS '리뷰';
COMMENT ON COLUMN TB_REVIEW.REVIEW_ID IS '리뷰 ID';
COMMENT ON COLUMN TB_REVIEW.USER_ID IS '리뷰 작성자 ID';
COMMENT ON COLUMN TB_REVIEW.RESTAURANT_ID IS '리뷰 대상 맛집 ID';
COMMENT ON COLUMN TB_REVIEW.REVIEW_RATING IS '리뷰 별점';
COMMENT ON COLUMN TB_REVIEW.REVIEW_CONTENT IS '리뷰 내용 원문';
COMMENT ON COLUMN TB_REVIEW.AI_SUMMARY IS 'AI가 요약한 리뷰 내용';
COMMENT ON COLUMN TB_REVIEW.AI_KEYWORDS IS 'AI가 추출한 키워드';
COMMENT ON COLUMN TB_REVIEW.CREATED_DATE IS '리뷰 생성 일시';
COMMENT ON COLUMN TB_REVIEW.CREATED_ID IS '리뷰 생성 ID';
COMMENT ON COLUMN TB_REVIEW.UPDATED_DATE IS '리뷰 수정 일시';
COMMENT ON COLUMN TB_REVIEW.UPDATED_ID IS '리뷰 수정 ID';

-- 리뷰 시퀀스
CREATE SEQUENCE SEQ_TB_REVIEW
    START WITH 1
    INCREMENT BY 1
    NOCACHE;