-- 권한
CREATE TABLE TB_RULE (
    RULE_ID NUMBER NOT NULL PRIMARY KEY,
    RULE_NAME VARCHAR2(50) NOT NULL UNIQUE,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_RULE IS '권한';
COMMENT ON COLUMN TB_RULE.RULE_ID IS '권한 ID';
COMMENT ON COLUMN TB_RULE.RULE_NAME IS '권한 이름';
COMMENT ON COLUMN TB_RULE.CREATED_DATE IS '권한 생성 일시';
COMMENT ON COLUMN TB_RULE.CREATED_ID IS '권한 생성 ID';
COMMENT ON COLUMN TB_RULE.UPDATED_DATE IS '권한 수정 일시';
COMMENT ON COLUMN TB_RULE.UPDATED_ID IS '권한 수정 ID';


--1	관리자	2025-07-08T17:05:11.390	admin	2025-07-08T17:05:11.390	admin
--2	일반 사용자	2025-07-08T17:05:11.406	admin	2025-07-08T17:05:11.406	admin

-- 권한 시퀀스
CREATE SEQUENCE SEQ_TB_RULE
    START WITH 1
    INCREMENT BY 1
    NOCACHE;