-- 태그
CREATE TABLE TB_TAG (
    TAG_ID NUMBER NOT NULL PRIMARY KEY,
    TAG_NAME VARCHAR2(100) NOT NULL UNIQUE,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);

COMMENT ON TABLE TB_TAG IS '태그';
COMMENT ON COLUMN TB_TAG.TAG_ID IS '태그 ID';
COMMENT ON COLUMN TB_TAG.TAG_NAME IS '태그 이름';
COMMENT ON COLUMN TB_TAG.CREATED_DATE IS '태그 생성 일시';
COMMENT ON COLUMN TB_TAG.CREATED_ID IS '태그 생성 ID';
COMMENT ON COLUMN TB_TAG.UPDATED_DATE IS '태그 수정 일시';
COMMENT ON COLUMN TB_TAG.UPDATED_ID IS '태그 수정 ID';

-- 태그 시퀀스
CREATE SEQUENCE SEQ_TB_TAG
    START WITH 1
    INCREMENT BY 1
    NOCACHE;