-- 사용자
CREATE TABLE TB_USER (
    USER_ID NUMBER NOT NULL PRIMARY KEY,
    RULE_ID NUMBER NOT NULL, -- 1은 관리자 2는 유저
    LOGIN_ID VARCHAR2(50) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_PASSWORD VARCHAR2(200),
    USER_EMAIL VARCHAR2(100) UNIQUE,
    USER_NICKNAME VARCHAR2(50) NOT NULL,
    USER_PROF_IMG_URL CLOB,
    USER_BIO VARCHAR2(200),
    HAS_VOTED CHAR(1) DEFAULT 'N',
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_ID VARCHAR2(100),
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_ID VARCHAR2(100)
);
ALTER TABLE TB_USER ADD VOTED_REGION NUMBER;

COMMENT ON TABLE TB_USER IS '사용자';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자 고유 ID';
COMMENT ON COLUMN TB_USER.RULE_ID IS '권한 ID';
COMMENT ON COLUMN TB_USER.LOGIN_ID IS '사용자 로그인 계정명';
COMMENT ON COLUMN TB_USER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN TB_USER.USER_PASSWORD IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_EMAIL IS '사용자 이메일 주소';
COMMENT ON COLUMN TB_USER.USER_NICKNAME IS '사용자 닉네임';
COMMENT ON COLUMN TB_USER.USER_PROF_IMG_URL IS '프로필 이미지 URL';
COMMENT ON COLUMN TB_USER.USER_BIO IS '사용자 자기소개';
COMMENT ON COLUMN TB_USER.HAS_VOTED IS '투표 여부 (Y/N)';
COMMENT ON COLUMN TB_USER.CREATE_DATE IS '계정 생성 일시';
COMMENT ON COLUMN TB_USER.CREATED_ID IS '계정 생성 ID';
COMMENT ON COLUMN TB_USER.UPDATED_DATE IS '계정 정보 수정 일시';
COMMENT ON COLUMN TB_USER.UPDATED_ID IS '계정 정보 수정 ID';
COMMENT ON COLUMN TB_USER.VOTED_REGION IS '투표한 지역 코드';

-- 시퀀스 이름
-- SEQ_TB_USER

CREATE SEQUENCE SEQ_TB_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE;