CREATE TABLE FOLLOWS (
    FOLLOWER_ID NUMBER NOT NULL,
    FOLLOWING_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID),
    FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWING_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CK_FOLLOWS_SELF_FOLLOW CHECK (FOLLOWER_ID != FOLLOWING_ID)
);

-- 7. 팔로우 테이블 (TB_FOLLOWS) 주석 추가
COMMENT ON TABLE TB_FOLLOWS IS '사용자 간의 팔로우 관계를 저장하는 테이블';
COMMENT ON COLUMN TB_FOLLOWS.FOLLOWER_ID IS '팔로우를 하는 사용자 ID (TB_USERS 참조)';
COMMENT ON COLUMN TB_FOLLOWS.FOLLOWING_ID IS '팔로우를 받는 사용자 ID (TB_USERS 참조)';
COMMENT ON COLUMN TB_FOLLOWS.CREATED_AT IS '팔로우 관계 생성일시';