CREATE TABLE TB_FOLLOW (
    FOLLOWER_ID      NUMBER NOT NULL,
    FOLLOWING_ID     NUMBER NOT NULL,
    FOLLOW_CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID),
    FOREIGN KEY (FOLLOWER_ID) REFERENCES TB_USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWING_ID) REFERENCES TB_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CK_FOLLOW_SELF_FOLLOW CHECK (FOLLOWER_ID != FOLLOWING_ID)
);

-- 7. 팔로우 테이블 (TB_FOLLOW) 주석 추가
COMMENT ON TABLE TB_FOLLOW IS '사용자 간의 팔로우 관계를 저장하는 테이블';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWER_ID IS '팔로우를 하는 사용자 ID (TB_USER 참조)';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWING_ID IS '팔로우를 받는 사용자 ID (TB_USER 참조)';
COMMENT ON COLUMN TB_FOLLOW.FOLLOW_CREATED_AT IS '팔로우 관계 생성일시';