create table tb_restaurant
(
    restaurant_id              number        generated by default as identity (start with 1 increment by 1 nocycle nocache),
    restaurant_name            varchar2(100) not null,
    restaurant_address         varchar2(200) not null,
    restaurant_phone_number    varchar2(20),
    restaurant_category        varchar2(50),
    restaurant_latitude        number(10,7),
    restaurant_longitude       number(10,7),
    restaurant_open_hours      varchar2(200),
    restaurant_break_time      varchar2(100),
    restaurant_holiday         varchar2(100),
    restaurant_parking_info    varchar2(200),
    restaurant_average_rating  number(2,1)   default 0.0,
    restaurant_review_count    number        default 0,
    created_date               date          default sysdate not null,
    created_id                 varchar2(100) not null,
    updated_date               date          default sysdate not null,
    updated_id                 varchar2(100) not null,
    constraint tb_restaurant_pk primary key(restaurant_id)
);

comment on column tb_restaurant.restaurant_id is '맛집 고유 ID (기본 키)';
comment on column tb_restaurant.restaurant_name is '맛집 이름';
comment on column tb_restaurant.restaurant_address is '맛집 주소';
comment on column tb_restaurant.restaurant_phone_number is '맛집 전화번호';
comment on column tb_restaurant.restaurant_category is '음식 카테고리 (예: 한식, 중식, 양식, 카페)';
comment on column tb_restaurant.restaurant_latitude is '맛집 위치 위도';
comment on column tb_restaurant.restaurant_longitude is '맛집 위치 경도';
comment on column tb_restaurant.restaurant_open_hours is '영업 시간 정보';
comment on column tb_restaurant.restaurant_break_time is '브레이크 타임 정보';
comment on column tb_restaurant.restaurant_holiday is '휴무일 정보';
comment on column tb_restaurant.restaurant_parking_info is '주차 정보';
comment on column tb_restaurant.restaurant_average_rating is '맛집 평균 별점';
comment on column tb_restaurant.restaurant_review_count is '맛집 리뷰 개수';
comment on column tb_restaurant.created_date is '맛집 정보 생성일자';
comment on column tb_restaurant.created_id is '맛집 정보 생성자 ID';
comment on column tb_restaurant.updated_date is '맛집 정보 수정일자';
comment on column tb_restaurant.updated_id is '맛집 정보 수정자 ID';
comment on table tb_restaurant is '7번국도 지역 맛집 정보를 저장하는 테이블';

create index idx_tb_restaurant_address on tb_restaurant (restaurant_address);
create index idx_tb_restaurant_category on tb_restaurant (restaurant_category);
create index idx_tb_restaurant_name on tb_restaurant (restaurant_name);

DROP TABLE tb_restaurant PURGE;